# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "ooniprobe.xcworkspace", scheme: "ooniprobe")
  end
  
  lane :upload_symbols do
    download_dsyms # this is the important part
    upload_symbols_to_sentry(
      auth_token: 'YOUR_AUTH_TOKEN',
      org_slug: 'ooni',
      project_slug: 'probe-ios',
    )
  end

lane :release do
  desc "Deploy a new version to the iTunesConenct"
#  build_app(scheme: "ooniprobe",
#     workspace: "ooniprobe.xcworkspace",
#     include_bitcode: true)
    deliver(
     submit_for_review: false,
     automatic_release: false,
#     skip_metadata: true,
     skip_screenshots: true,
     skip_binary_upload: true
    )
   end
end
